### ISSUE TITLE
Curating a cell_subset with more than one cell_subset

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#521] opened 2021-04-12 16:12 UTC
We are working on curating a study from a new COVID-19 data set. The researchers have cell sorted the samples as a _mix_ of circulating "antibody secreting cells" (http://purl.obolibrary.org/obo/CL_0000946) and isotype switched (IgD-) memory B cells (http://purl.obolibrary.org/obo/CL_0000972).

There is no way for a `Sample` to have an array of ontologies for the cell subset so we can't currently represent this correctly in the AIRR Standard if I am not mistaken... Advice?

**Comment by scharch** [comment] 2021-04-12 16:24
My instinct is least common denominator, which looks like http://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0001200 though I'm having trouble navigating the ontology properly...

**Comment by bcorrie** [comment] 2021-04-12 17:03
Would this be a common thing that researchers would do (have multiple cell types in the same cell sorting process)? If so, should the standard capture that by allowing for an array?

**Comment by scharch** [comment] 2021-04-12 17:16
I don't think so. My feeling is that, if there is some strategy for demultiplexing (you can tell the cell types apart), that should be done and then curate them separately, each with the appropriate single ontology. If you can't tell them apart, then I think the LCD approach is the way to go from the perspective of reusability --if I am searching for isotype-switched memory B cells, I am probably not interested in a sample that has a different cell type mixed in indistinguishably. Worse, knowing me, I'm likely to use the search results without reading carefully enough to even realize that repertoire Z has an array on cell_subset, and then my analysis will be invalid... 😬

**Comment by bussec** [comment] 2021-04-13 01:40
My 2 cents:

1. Class-switched cells and "antibody-secreting cells" (ASC, see 2.) have different characteristics and therefore should have be sorted separately. I agree with @scharch that you should demultiplex if this is possible (e.g., single-cell experiment) and go for the the LCD if it is not.
2. I assume that this is peripheral blood (as you wrote "circulating"). In this case, an ASC (CL:0000946) will practically always be a plasmablast (CL:0000980), which is not only a subclass of ASC but also a subclass of "mature B cell" (CL:0000785). Importantly, the latter one is also a super-superclass of "class switched memory B cell" (CL:0000972) and therefore a more specific LCD than the "lymphocyte of B cell lineage" (CL:0000945) that would be the LCD of CL:0000946 and CL:0000972.
3. How often do you see such mixed populations in your annotation work? I would be hesitant to make `cell_subset` an array as I do not see to many legitimate use cases for it.

**Comment by bcorrie** [comment] 2021-04-13 15:30
> 3\. How often do you see such mixed populations in your annotation work? I would be hesitant to make `cell_subset` an array as I do not see too many legitimate use cases for it.

First time I believe - thanks for the advice. We will touch base with the researchers to see if they object. We will probably use cell_phenotype to describe the two types of cell's that repertoire would contain. Does that make sense...

**Comment by bussec** [comment] 2021-04-13 15:47
I think that's a reasonable solution. Will add some guidance on this to the docs as part of the `ontovoc-04-21` branch.

**Comment by kira-neller** [comment] 2021-04-13 16:16
Thanks all for your comments. @bussec I have a question about using "mature B cell" (CL:0000785) as the LCD. These cells are described as: A B cell that is mature, having left the bone marrow. Initially, these cells are IgM-positive and **IgD-positive**, and they can be activated by antigen. 

However, cell_phenotype [of this mixed population] provided by authors is: CD3-CD14-CD15-CD56-CD19+**IgD-** 

Is "mature B cell" (CL:0000785) still the best LCD, given that it specifies **IgD+**?

**Comment by bussec** [comment] 2021-04-13 17:11
@kira-neller thanks for pointing this out. I would still use CL:0000785 as annotation, although it mentions "IgD-positive" in the written description. Reasoning is as follows:
1. The description states that "Initially, these cells are IgM-positive and IgD-positive [...]", which I interpret as "the cell must have passed through the IgM+ IgD+ stage, but it may not express these markers anymore".
2. *Mature naive* B cells are usually required to be IgD+, however, these have their own term ("naive B cell", CL:0000788), which in CL is a subclass of "mature B cell". If you look at the [term relations at OLS](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000788) you see that for this term, IgD expression is a formally defining criterion, while it is not for "Mature B cell".
3. The "Mature B cell" term contains multiple subclasses that describe class-switched cells, which are nearly exclusively IgD-.

**Comment by kira-neller** [comment] 2021-04-15 16:19
Thanks @bussec for adding documentation regarding this. I see it here: https://github.com/airr-community/airr-standards/compare/ontovoc-04-21

I have one suggestion - perhaps state explicitly that only one term is allowed for cell_subset?

By the way, we confirmed the proposed changes with authors of the study and they are in agreement :)

**Comment by bussec** [comment] 2021-04-22 22:53
@kira-neller Ok, I added another paragraph.

Can we close this issue?

**Comment by kira-neller** [comment] 2021-04-22 23:03
Looks good to me!

**Closed** 2021-04-23 16:53 UTC
