### ISSUE TITLE
Create a FairShairing.org record for DataRep AIRR TSV

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#381] opened 2020-04-20 22:27 UTC
We have a record for MiAIRR, should we create a record for the AIRR TSV file format as per the Data Rep paper??? 

I can create this if I get the thumbs up...

**Comment by bussec** [comment] 2020-04-27 11:24
This is a duplicate of #306, therefore I will close it. But please feel free to go ahead ;-)

**Closed by bussec** 2020-04-27 11:24 UTC
Labels: duplicate
