### ISSUE TITLE
Should we deprecate clone_id from Rearrangement?

### ISSUE THREAD

**Issue by scharch** [airr-community/airr-standards#446] opened 2020-07-27 19:35 UTC
What the title says. Partially related to #439 suggesting that the on-disk representations only contain unidirectional linkages, but more about the desire to avoid duplicating `Rearrangement` data. If the `Rearrangement` object is static, that would imply it should only have fields for static properties. There was some side discussion in #409 of whether `cell_id` qualifies (I think it does), but it seems pretty clear that `clone_id` does not. I expect it will be relatively common to use multiple parameters/tools for determining clonality in a single `Repertoire`, as well as combining `Repertoire`s in different ways to analyze clones.

**Comment by javh** [comment] 2020-07-27 19:59
I'm inclined to go with "no". For an on-disk file representation used for analysis, I think we'll be better off having `cell_id`, `clone_id`, etc in the Rearrangement TSV despite the duplication of data caused by keeping/comparing analyses done under different parameters.

But, maybe that's the wrong solution for a representation in a database or a query interface. Maybe those different needs require different data structures?

The fields are optional though, so I if a given tool would rather store a list of `sequence_id` values in `Clone` instead of have `clone_id` values in Rearrangement, I think we can do that with the schema as is. You'd just pick the optional fields appropriate to how you want to structure your data. Which, doesn't really solve #439... Maybe that becomes a case of pick one, but not both: linking identifiers can defined (1) bottom-up (filesystem) or (2) top-down (database).

**Comment by javh** [comment] 2021-04-05 17:48
Closing this. (Reopen if this comes back up during the process of finalizing the lineage, but I'm suspecting not.)

**Closed by javh** 2021-04-05 17:48 UTC
