### ISSUE TITLE
MiAIRR table for v1.2 release (stable) is broken!!!

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#397] opened 2020-05-16 18:40 UTC
Hi All,
I just noticed that the link to the table on this page:

https://docs.airr-community.org/en/stable/miairr/introduction_miairr.html

is broken. As a result, I don't think there is a way to get to the table of AIRR terms in the current spec on the stable docs branch... Not sure how long this has been broken!

**Comment by bcorrie** [comment] 2020-05-16 18:44
I notice that the table is linked to the TSV file on master branch - which no longer exists... I thought the stable branch was linked to the 1.2.1 tag (the most recent numerical tag). Not sure how these things get pushed to docs site - so not sure what the right fix is.

**Comment by bcorrie** [comment] 2020-05-16 18:46
I guess this will be less important when we release v1.3, but we should probably still fix?

**Comment by javh** [comment] 2020-05-16 18:53
Duplicate of #393. 
I'm working on it. Didn't have time during the week to finalize the fixes. It builds in the docs-tables branch though.

**Comment by javh** [comment] 2020-05-16 19:01
I guess we could restore this link by putting the old TSV back into master temporarily, but yuck.

**Comment by bcorrie** [comment] 2020-05-17 22:33
Probably not worth fixing for 1.2 and just fix through the v1.3 release???

**Closed** 2020-05-20 17:24 UTC
