### ISSUE TITLE
AIRR TSV errors from IgBlast 1.12.0

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#190] opened 2019-03-15 21:27 UTC
IgBlast doesn't have a public bug ticket system (AFAIK) so I'm listing errors I've found here so people are aware of them. I will follow up with Jian @ NCBI about them.

I'm current testing with mouse TCR sequences. These can be reproduced by going to the [IgBlast page](https://www.ncbi.nlm.nih.gov/igblast/igblast.cgi?CMD=Web&SEARCH_TYPE=TCR&LINK_LOC=igtab), select TCR, mouse germline, and set the alignment format output to AIRR.

bug 1: A sequence that produces zero alignments will produce a row with the `sequence` field but all other fields are blank. While most fields being blank is expected for a non-alignment, there should be `sequence_id` so you track back to the original sequence, and booleans like `productive` and `rev_comp` should have F instead of relying upon a default value.

Here is an example sequence:

```
>M03100:71:000000000-AEA1J:1:1101:16364:2374
GAAATATCCGAAAGTGTTAACTTCTGCGTCATGGAAGCGATAAAACTCTGCAGGTTGGAT
ACGCCAATCATTTTTATCGAAGCGCGCATAAATTTGAGCAGATTTGTCGTCACAGGTTGC
GCCGCCAAAACGTCGGCTACAGTAACTTTTCCCAGCCTCAATCTCATCTCTCTTTTTGCG
TTCTGCTTCAATATCTGGTTGAACGGCGTCGCGTCGTAACCCAGCTTGGTAAGTTGGATT
AAGCACTCCGTGGACAGATTTGTCATTGTGAGCATTTTCATCCCGAAGTTGCGGCTCATT
CTGATTCTGAACAGCTTCTTGGGAAGTAGCGACAGCTTGGTTTTTAGTGAGTTGTTCCAT
TCTTTAGCTCCTAGACCTTTA
```

**Comment by schristley** [comment] 2019-03-15 21:31
bug 2: Some sequences produce a blank `vj_in_frame` field. This isn't a required field so this would just be a warning, but better that it have either T or F so that a default value isn't relied upon.

Here is a test sequence:
```
>M03100:71:000000000-AEA1J:1:1101:13974:2255
CAGCAGAGACGAGGCCAGGGTTTTCCCAGTCACGACATCGCTGAAGACAGAAAGTCCAGT
ACCTTGATCCTGCCCCACGCTACGCTGAGAGACACTGCTGTGTACTATTGCATCGCCTAA
ACTGGGGCAAACAACCTCTTCTTTGGGACTGGAACGAGACTCACCGTTATTCCCTATATC
CAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCTAAATCCAGTGACTGAACCA
```

**Comment by schristley** [comment] 2019-03-15 21:38
bug 3: Some sequences produce a blank `productive` field. This is a required field so the blank will trigger a warning during validate. This particular test sequence also produces a blank `stop_codon` and `vj_in_frame` fields.

Here is a test sequence:
```
>M03100:71:000000000-AEA1J:1:1101:17754:2305
ACGCAAAGCATTGGGATTATCATAAAACGCCTCTAATCGGTCGTCAGCCAACGTGAGAGT
GTCAAAAACGATAAACCAACCATCAGCATGAGCCTGTCGCATTGCATTCATCAAACGCTG
AATAGCAAAGCCTCTACGCGATTTCATAGTGGAGGCCTCCAGCAATCTTGAACACTCATC
CTTAATACCTTTCTTTTTGGGGTAATTATACTCATCGCGAATATCCTTAAGAGGGCGTTC
AGCAGCCAGCTTGCGGCAAAACTGCGTAACCGTCTTCTCGTTCTCTAAAAACCATTTTTC
GTCCCCTTCGGGGCGGTGGTCTATAGTGTTATTAATATCAAGTTGGGGGAGCACATTGTA
GCATTGTGCCAATTCATCCATTAACTTCTCAGTAACAGATACAAACTCATCACG
```

**Comment by schristley** [comment] 2019-03-15 21:46
bug 4: The `locus` field has incorrect values. For my mouse TCR sequences, I'm seeing values like `VA`, `VB`, `VD`, `VG`. Some sequences have a value `NON` which presumably means no locus but in this test case, the sequence has a TRBV gene in `v_call`

here is a test sequence:
```
>M03100:71:000000000-AEA1J:1:1101:17754:2305
ACGCAAAGCATTGGGATTATCATAAAACGCCTCTAATCGGTCGTCAGCCAACGTGAGAGT
GTCAAAAACGATAAACCAACCATCAGCATGAGCCTGTCGCATTGCATTCATCAAACGCTG
AATAGCAAAGCCTCTACGCGATTTCATAGTGGAGGCCTCCAGCAATCTTGAACACTCATC
CTTAATACCTTTCTTTTTGGGGTAATTATACTCATCGCGAATATCCTTAAGAGGGCGTTC
AGCAGCCAGCTTGCGGCAAAACTGCGTAACCGTCTTCTCGTTCTCTAAAAACCATTTTTC
GTCCCCTTCGGGGCGGTGGTCTATAGTGTTATTAATATCAAGTTGGGGGAGCACATTGTA
GCATTGTGCCAATTCATCCATTAACTTCTCAGTAACAGATACAAACTCATCACG
```

**Comment by schristley** [comment] 2019-03-15 21:49
bug 5: Sequences that align with the reverse complement have the string "reversed|" prefixed to the `sequence_id`. This could be problematic for codes that use `sequence_id` for matching entries across files.

here is a test sequence:
```
>M03100:71:000000000-AEA1J:1:1101:15958:2317
CGAAAGACCAGGTATATGCACAAAATGAGATGCTTGCTTATCAACAGAAGGAGTCTACTG
CTCGCGTTGCGTCTATTATGGAAAACACCAATCTTTCCAAGCAACAGCAGGTTTCCGAGA
TTATGCGCCAAATGCTTACTCAAGCTCAAACGGCTGGTCAGTATTTTACCAATGACCAAA
TCAAAGAAATGACTCGCAAGGTTAGTGCTGAGGTTGACTTAGTTCATCAGCAAACGCAGA
ATCAGCGGGATGGCTCTTCTCATATTGGCGCTACTGCAAAGGATATTTCTAATGTCGTCA
CTGATGCTGCTTCTGGTGTGGTTGATATTTTTCATGGTATTG
```

**Comment by schristley** [comment] 2019-03-15 22:06
bug 6: This sequence produces an odd result. It is flagged as `productive=T` yet it has no `junction_aa` or `cdr3_aa`. If you run this on the IgBlast website and produce the normal HTML alignment output, the Alignment Summary table shows a CDR3 with positions and length, but the detailed alignment does not have the CDR3 marked.

```
>M03100:71:000000000-AEA1J:1:1101:11355:2030
GTTCTTCTCTTTTTCCCTTTTTTTCCCATTCACGACGGACAAGTTTCTCATCAACCATGC
AAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTA
CATCTGCAGTGCTAGAGACAGACAGGGGCGAGATGAAAAACTGTTTTTTGGCAGTGGAAC
CCAGCTCTCTGTCTTGGAGGACCTGAACAAGGTGTTCCCACCCGAGGTCGCTGTGCTTGA
GCCATCAGAAGCAGAGATCTCTCCTGAA
```

**Comment by bcorrie** [comment] 2019-03-16 00:00
Hi @schristley - thanks for reporting these... We have seen bug 5 and bug 1 in passing... We don't use igblast for our curation, so we have run across these oddities in some of the data we have produced from igblast, but didn't dive in to the details as we were primarily using this to test our data loading on "well formed" igblast AIRR TSV output. We were confused as to where these came from, but didn't dive into the details as we don't use igblast for our production curation.

**Comment by jianye00** [comment] 2019-03-19 18:43
Hi Scott,

Thanks for the message.  We can add some missing things you saw but many other things you saw are not actually bugs.

1.  Yes we can add sequence_id and rev_comp fields for sequences that don't have any similarity to a germline V gene.  But we should not add the productive field there since it's unknown of course.

2.  vj_in_frame blank.  

The vj frame is not guaranteed since a tool may not be able to determine it for various reason.  In this case, the matched J gene is  TRAJ36*01 which is a pseudogene and its reading  frame is not defined (we took  that information from imgt web site (http://www.imgt.org/IMGTrepertoire/Proteins/alleles/index.php?species=Mus%20musculus&group=TRAJ&gene=TRAJ-overview ) and that is not listed there.  

I suppose we could annotate the reading frame ourselves but there is no guarantee that a pseodogene can be confidently annotated.

3.  Blank productive field.

This field is also not guaranteed since some sequences may not have a J gene at all and therefore whether it's productive or not is unknown (productive means a productive V(D)J alignment).  In your case, the sequence has only 18 bp alignment with V gene and mostly likely this is not a TCR at all.  Therefore it is left blank to indicate unknown status (a blank (null) is allowed for required field per  AIRR specs,  http://docs.airr-community.org/en/latest/datarep/overview.html#datarepresentations).  But we can certainly change to a visible string value if users like and the AIRR specs spell it  out.

4.  Non field.   

Yes we should report that as VB instead of NON.  Even though this sequence only has 18 bp alignment to VB gene, we still need to report as is.  I guess the extremely low homology to VB gene somehow makes igblast ignore that information somewhere in the code.  We need to look at the reason but this should be a very much corner case.

5.  "reversed" appended to sequence id for reversed sequences. 

IgBlast has been appending that to sequence id from day 1 in the alignment section for alignment view format or for the tabular format.  The rational was to remind users that this is the reversed complimented sequence.   But since AIRR format  is mostly for robot to read and there is already a rev_comp field, I suppose we can get rid of that if users really like that.

6.  No CDR3.

Showing CDR3 is not guaranteed,  for example some sequence is truncated and does not have that at all.  What you see in the summary table is just the CDR3 part in the V gene itself (it is also called CDR3-IMGT (germline) ).  The real CDR3 is would have been reported in Sub-region sequence details table.

In your case, the J gene has very long 28 bp deletion at the beginning of J gene which is beyond the CDR3 end (at position 21) and igblast could not determine where the CDR3 ends hence no reporting).  But I suppose we can look at this to make igblast smarter in determining CDR3 even though a clear boundary is not there.

**Comment by schristley** [comment] 2019-03-19 19:43
Thanks for the feedback Jian. Your responses make sense to me. You bring up a good point about the boolean flags in that the value might be unknown. A similar point applies to the locus, if it cannot be determined, what value should we use.

**Comment by jianye00** [comment] 2019-03-19 19:58
since we already report blank field for things not defined or not found, we should also report blank (empty string) for locus that is not found.  But again we certainly can change that if people think there is a better way.

**Comment by javh** [comment] 2019-03-19 20:37
Yeah, empty is string is the official missing data value.  So, `NON` to `""`, `VB` to `TRB`, and so on.

**Comment by jianye00** [comment] 2019-04-11 21:35
Here are the things we'll put for the next igblast release (coming soon) for the AIRR format.

1. Restore sequence id for no result case. 

2. Change undefined locus type (NON, N/A) to empty string.

3. Not append "reversed" to sequence id.  User should check the rev_comp field to determine the sequence orientation.

4. Use standard locus names such as IGH, TRB instead of traditional VH, VB etc.

Let me know if there is any question.

**Comment by jianye00** [comment] 2019-04-29 17:30
The new igblast release 1.14 addressing the issues we discussed in now on our ftp site.

**Comment by ssnn-airr** [comment] 2019-04-29 19:15
@jianye00 I have a question not formats/representation related, but maybe of interest for others in this thread, as we all are trying to get a good sense of the differences in annotations coming from different tools.

We have noticed some inconsistency in the IgBLAST `CDR3 nucleotide seq` and `CDR3 amino acid seq` values. For example you can get the CDR3 nt sequence `GCCAGGAGGTGTTACTATGGTTCGGAGATGGGGACCTGGTTCGACCCC` and the translation `PGGVTMVRRWGPGSTP`. But if you do the translation of the nucleotide sequence in frame 1 you get `ARRCYYGSEMGTWFDP`. IMGT, for the same input fasta sequence, reports the same CDR3 and the translation in frame 1 for that sequence. Why this difference in the translation? Is this a bug? Is this related to indels and frame shifts? Thanks!

An example sequence:
>test1
cggctcngantggtgagccttcacagaccctgtccctcacctgcgctgtctctggtggctccatgagcagtggtgattactcctggagctggatccggcagccaccagggaagggcctggagtggattgggtacatctatgatagtgggagcacctactacaacccgtccctcaagagtcgattcaccatatcaatagacaggtccaagaaccagttctccctgaagctgacctctgtgaccgccgcggacacggccgtatattactgtgccaggaggtgttactatggttcggagatggggacctggttcgacccctggggccagggaaccctggtcaccgtctcctcagcctccaccaagggcccatcggtcttccccctggcaccctcctccaagagcacctctgggggcacagcggccctgggctgcctgnnnannnnnnnnnnaa

**Comment by jianye00** [comment] 2019-04-29 20:30
This is not a bug.  A nucleotide sequence has 3 frames and it can have different amino acid sequences depending on which frame it uses.  Igblast always considers the nucleotide deletion/insertion in actual translation since that's what you will actually get.  As a result, it is quite possible the CDR3 does not has amino acid translated in frame 1 if you have a base deletion or insertion in front.  In your case, there is a single base deletion at the beginning part of FWR1 (represented by a dash):

 GA NTG GTG A-GC CT

That renders the frame shift of your sequence (so igblast translates frame is now A-GC).

IMGT tool by default ignores deletion/insertion in performing nucleotide sequence alignment. and therefore you see the alignment very bad (meaning most mismatches are aligned) at the front part of FWR1.  Now imgt tool does have an option that allows you to include deletion/insertion and that option is "Search for insertions and deletions in V-REGION". If you select that, then you'll see the exact same nucleotide alignment as igblast produces (the deletion is represented by a dot):

ga ntg gtg a.g cct

However, imgt chose to ignore the missed nucleotide in translation and therefore it skips the codon that has the gap (a.g) in translation.

Different tools can choose to do different things.  But we thought we should always faithfully translate the actual nucleotide sequences since the actual translation machinery does not skip the deletion/insertion.

**Comment by ssnn-airr** [comment] 2019-04-30 14:10
Thanks for the explanation @jianye00 , this was my interpretation of what was happening, based on 3 sequences I inspected manually, that IgBLAST was doing the translation in the context of the alignment whole sequence, but IMGT was focusing on the junction. I don't know what is best. I guess IMGT considers that the aligned/anchored junction must be in frame, and therefore translates in frame 1. I am not sure what happens if indels fall in the junction. I kept notes for this sequence I used as an example here, but not for the other 2 sequences, and I don't remember were the indels were happening.
@javh @schristley @bcorrie Does the current `Rearrangement` specification allow to easily figure out what style of translation the `junction_aa` field is using, other than doing the translation of `junction` and checking if it matches `junction_aa`? Do you think this different choice is something to be tracked? I imagine, if someone wanted to combine datasets to compare amino acid properties of the CDR3, this could be relevant. I am not sure how many sequences would be falling in such scenario, probably the impact is small. We found this to happen in 3 out of ~100.

**Comment by jianye00** [comment] 2019-04-30 14:53
@ssnn-airr The V-J frame is  also reported as in-frame by igblast.  It's just that there is a frame shift that makes this sequence non-productive.  If there is a specific need to just focus on CDR3 and ignore its actual translation in the context of the whole sequence , then we could add an option for that.   By the way, it does not matter if there are indels in the V-J junction, as long as the junctional sequence length between the V and J reading frames is a whole number divisible by 3, it's in-frame, otherwise, out-of-frame.

**Comment by ssnn-airr** [comment] 2019-04-30 15:17
Attached my notes, in case anyone interested in visualize what we are talking about. Not the best photo quality, sorry.
![aln-notes](https://user-images.githubusercontent.com/20683719/56972774-96462c80-6b39-11e9-8709-37a22bd1d74f.jpg)

**Comment by ssnn-airr** [comment] 2019-04-30 19:37
@jianye00 Thanks for the comments. Let's see if others jump in and share their opinion. I think that to define being in frame, and determine the translation frame, one has to consider also the conserved aminoacids that are a prerequisite of having an Ig, and in this case in particular the ones that mark the boundaries of the junction. So the translation of the VDJ sequence should produce them. But it seems to me, the translation in the context of the whole sequence, with the frame shift, could end in not getting these conserved aminoacids? In the example above, IMGT is considering the junction `CARRCYYGSEMGTWFDPW` (notice C and W conserved aminoacids), but IgBLAST considers `VPGGVTMVRRWGPGSTPG` (V and G, no conserved aa).

**Comment by jianye00** [comment] 2019-04-30 19:55
@ssnn-airr I'd say depending on what you are doing.  For general purpose where people put a nucleotide Ig sequence and ask what amino acids they will get, then you definitely have to consider frame since this is what you'll actually get (the conserved codon are there but you'll not actually get it due to frame shift).  However, if people are only studying some theoretical amino acid property of CDR3, then I can see you might not need to consider the frame.  As I said, earlier, if there is such a need, we could add an option to ignore frame.

**Comment by jianye00** [comment] 2019-05-01 16:55
@ssnn-airr Just to mention that instead of agonizing over what to do with the CDR3 for non-productive sequences, if your purpose is to analyze the functional repertoire, many studies simply exclude the non-productive sequences.

**Comment by javh** [comment] 2019-05-01 17:41
No, there isn't a specific mechanism in `Rearrangement` to define the assumptions underlying translation strategy (or alignment). I'm not certain we could define one in a way that is exhaustive of how all tools choose to approach these problems without being too complex/burdensome.  I think this is probably best covered by specifying the reference alignment tool and version in the metadata.

I'd say that defining the translation frame based on the junction is an error correction strategy.  Ie, if the junction is a multiple of 3 with the expected start/end motifs, you then assume an earlier indel is a sequencing/PCR artifact. I think that's usually true for indels early in the amplicon, especially if they are in the primer region. But, then it's not a faithful translation of the observed sequence...

Not sure if adding an option to ignore the frame is the right call or not. If you were to add an option, maybe it would make more sense for the option to toggle between defining the translation frame of the _full_ sequence based on the (b) germline start vs the (b) junction start. Then you'll, hypothetically, get more valid translation out of those cases where you have an indel in the primer region. But, I think that would only address that specific artifact.  If the sequences done on the 454, then you'll probably have indels throughout the observed sequence and need to do something a lot more complex to try to correct for that.

**Comment by jianye00** [comment] 2019-05-01 19:07
Igblast is designed as a general purpose tool and it does not consider any error correction (which involves another whole different set of logic and uses cases).  User needs to decide if their input sequence has error or not.  There are legit cases  where indels are not errors at all (for example, pseudogenes, mutations).   I think error corrections should be handled before a user puts the sequences into annotation tool.

**Comment by javh** [comment] 2019-05-03 19:10
Thanks, @jianye00. My takeway is that this is out of scope for igblast. I'm going to close this, but feel free to reopen if appropriate.

**Closed by javh** 2019-05-03 19:11 UTC

**Comment by jianye00** [comment] 2019-05-03 19:30
Thanks you all for discussion.  Don't hesitate to contact me if you have any issues.
