### ISSUE TITLE
Coordinate with IgBlast to produce AIRR format output

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#75] opened 2018-01-09 17:53 UTC
Jian Ye is the contact at NCBI. If I'm thinking about this correctly, IgBlast is an aligner so it would technically be producing our alignment (hit table) output format, and not the rearrangements format? Or are we thinking that IgBlast could also produce a rearrangement file, e.g. by picking the top VDJ alignment?

**Comment by schristley** [comment] 2018-01-10 19:30
From email from Jian:

> Currently, we are trying to make igblast produce the rearrangement result as defined by the format group.
 
> http://airr-formats.readthedocs.io/en/latest/rearrangements/
 
> Yes the results will be based on the top germline hit.
 
> As for alignment result, that’s something for the future phase when things become more clear about what it is and how we should do it (for example, do we produce both alignment data and rearrangement data in the same or different output? etc.).  Most people would just want rearrangement data based on top alignments anyway and making  AIRR rearrangement format available itself will make lots of people happy.

**Comment by schristley** [comment] 2018-01-29 17:26
Sample output from IgBlast

[sampleout.txt](https://github.com/airr-community/airr-standards/files/1674587/sampleout.txt)

**Comment by javh** [comment] 2018-02-08 17:33
I haven't gotten to the point where I can test this yet, but a few notes:

+ `sample_id` seems consistently empty in every file we generate. This shouldn't be mandatory. Also, see #82 for the status of this field.
+ We should probably add `stop`, `chain_type` and `v_j_in_frame` to the spec as optional fields. Not sure about the names. Maybe also `mutated_invariant`
+ We need to make sure our definition of the `functional` field is clear. Eg, do the values in `v_j_in_frame` and/or `stop` imply a value for `functional`.

**Comment by javh** [comment] 2018-02-08 18:56
From Jian:

> Igblast’s  “functional” definition has been an in-frame rearrangement plus non-stop codon.

**Comment by javh** [comment] 2018-02-08 19:01
According to IMGT, `FUNCTIONAL` is a property of the germline and `PRODUCTIVE` is a property of the rearrangement (recombined V(D)J gDNA or RNA).

> FUNCTIONAL: A germline entity (V-GENE, D-GENE or J-GENE) or a C-GENE is functional if the coding region has an open reading frame without stop codon, and if there is no described defect in the splicing sites, recombination signals and/or regulatory elements.

> PRODUCTIVE:  A rearranged IG or TR (genomic or cDNA) entity is productive if the coding region has an open reading frame, with no stop codon and no defect described in the initiation codon, splicing sites and/or regulatory elements, and an in-frame JUNCTION.

> UNPRODUCTIVE:  An unproductive rearranged IG or TR (genomic or cDNA) entity is characterized by an out-of-frame JUNCTION and/or the presence of stop codon(s) and/or frameshift mutation(s), and/or a defect described in the splicing sites and/or the regulatory element(s), and/or unusual features (TRANSLOCATED, GENE FUSION...) and/or changes of conserved amino acids demonstrated as leading to uncorrect folding.

**Comment by jianye00** [comment] 2018-02-08 20:13
Well igblast has been using the name "productive" in all current formats , consistent with IMGT's term.  But since the  AIRR format only has the "functional" field name, not "productive", the igblast's new AIRR format also uses the  "functional" name.  If AIRR "functional" definition really is the same as what "productive" means, then please change that to "productive" and we'll update it.

**Comment by BusseChristian** [comment] 2018-02-08 20:52
I was not aware of IMGT's definition of these terms. IMO the usage of `productive` to indicate the status of the VDJ joint matches with wet-lab immunology terminology. However, `functional` rather refers to the ability of the encoded protein to mediate a certain effect (e.g. cell activiation / antigen recognition). So, it is good that you changed it 😃

**Comment by javh** [comment] 2018-03-10 20:44
I grabbed the development version of IgBLAST and I'm going through tests now using `-outfmt 19`.

Here's a summary of the relevant changes from #89 to the output file:

+ Rename `rearrangement_id` to `sequence_id`.
+ Rename `chain_type` to `locus`. Consider swapping nomenclature to IGH, IGK, IGL, TRA, TRB, TRD, TRG.
+ Rename `v_j_in_frame` to `vj_in_frame`.
+ Rename `functional` to `productive`.
+ Rename `junction_nt` and `junction_nt_length` to `junction` and `junction_length`.
+ Rename `v_start`, `v_end`, etc to `v_sequence_start`, `v_sequence_end`, etc.
+ Rename `v_germ_start`, `v_germ_end`, etc to `v_germline_start`, `v_germline_end`, etc.
+ Rename `np1_seq` and `np2_seq` to `np1` and `np2`.
+ Remove `sample_id`.
+ Add `sequence_alignment` and `germline_alignment` (may be empty).

We also added a bunch of extra optional fields for translations (`*_aa`) if you need them, but they aren't in the required section of the schema.

Looking through the results the only discrepancies with the standard I notice are:

+ Looks like the positions are 1-based closed intervals (BLAST style) instead of 0-based open intervals (python style).  Just need to subtract 1 from the `*_*_start` values.
+ The CIGAR doesn't look quite right, but we are deviating from the normal use slightly.  The error might be on my end though. I'll investigate and update later when I've figured it out.

**Comment by jianye00** [comment] 2018-03-12 19:07
Yes igblast as well as other ncbi tools I know of use 1-based sequence coordinates when the result is presented to users (although ncbi internal data structures are  all 0-based but they are hidden from users).  When people talk about sequence coordinates,  like "where is IGHV69-1 located on chromosome 14"?  most people use the actual coordinates (i.e., 1-based).   I suppose we could potentially change  to 0-based but this would create discrepancy with all other things we have been doing.  Is this really necessary?  what problem it causes if AIRR format is 1-based?

**Comment by javh** [comment] 2018-03-12 19:18
It wouldn't cause a problem if the standard was 1-based, closed intervals. We just put it to a vote awhile ago and the majority was overwhelmingly in favor of 0-based, half-open intervals.

Personally, I don't have much of an opinion as to whether we should go with python/C style indexing or R/BLAST style indexing. I'm not opposed to reopening the debate either. (I still have no opinion - provided whatever API we write does the appropriate conversion for R and python).

**Comment by jianye00** [comment] 2018-03-12 19:34
If it's mainly intended for convenience to work with API or tools, then it seems to me that this reason is just too small since it's trivial to adjust for that on API or tool side.  I'd think giving users the real coordinates (1-based) is better.

**Comment by schristley** [comment] 2018-03-12 19:55
This tends to be one of those unsolvable debates as people pick the representation that's easiest for their language, as there is no "real" underlying truth. I'm fine with doing the vote over, and try to get a larger participation from the tool developers. Regardless of the outcome, one subset will be satisfied and the other subset will be annoyed.

We could also go the route of adding an optional field that indicates the coordinate system. There would be a default but the field could indicate otherwise. That would force all tools to handle transformation.

It would be nice actually if the reference library could make this transparent for tools, by translating to whatever the tools wants, but not every tool will use our libraries.

**Comment by javh** [comment] 2018-03-12 20:02
> It would be nice actually if the reference library could make this transparent for tools, by translating to whatever the tools wants, but not every tool will use our libraries.

This was in the roadmap for the R library. And I very much agree. If we reopen the debate, I think that's the perspective we should look at it from. So that's really 3 questions:

1. What's the indexing scheme for the TSV format?
2. What's the indexing scheme for the python library after import?
3. What's the indexing scheme for the R library after import?

**Comment by schristley** [comment] 2018-03-12 20:09
> This was in the roadmap for the R library. And I very much agree.

The additional challenge to make this automatic is that the library needs to know which fields need to be transformed. While we can tag fields in the spec, what to do about fields that are not in the spec? Maybe extend the library so that tools adding fields must provide a flag to indicate this, and maybe this is sufficient?

> 1. What's the indexing scheme for the TSV format?

debatable.

> 2. What's the indexing scheme for the python library after import?

python is 0-based, so 0-based

> 3. What's the indexing scheme for the R library after import?

R is 1-based, so 1-based

**Comment by jianye00** [comment] 2018-03-12 20:19
Adding a  coordinate flag for 0 or 1 based is fine if we really want to be more explicit.

**Comment by javh** [comment] 2018-03-12 20:23
My vote is that adding a coordinate flag is more complex than necessary. I'd prefer to just pick one and stick with it.

I don't think we need to worry about fields that aren't in the spec, though we could maybe account for them in the libraries by having an argument for the user to specify additional non-spec start/end fields.

**Comment by javh** [comment] 2018-03-15 17:19
For what it's worth, I was on the germlines wg call the other day and they sounded pretty unanimous about using 1-based indexing for defining polymorphisms.

**Comment by javh** [comment] 2018-03-15 22:37
Okay, I looked closer at the CIGAR strings.  Part of the issue is that I had an off-by-one indexing error in my code that converts BTOP to CIGAR. I did some spot checking and here's what we currently have.

Example for the same sequence, run through IgBLAST, *changeo* is me parsing from the BTOP string and *igblast* is the `-outfmt 19` CIGAR strings. The second changeo line is just conversion between the `X`/`=` and `M` formats for illustration.

```
v_cigar
changeo:       136S  154=1X140=
                     295M
igblast:       136S  295M  97S

d_cigar
changeo:  3N  439S  15=
                    15M
igblast:      439S  15M  74S

j_cigar
changeo:  2N  454S  4=1X1=1X39=
                    46M
igblast:      454S  46M  28S
```

Everything looks the same to me except the missing `N` operator in the igblast result. The idea being that the initial `S` operator lets us determine `query start` and the initial `N` gives us `subject start`. Ie, `S` and `N` are duplicate information with the fields like `v_sequence_start` and `v_germline_start`, as these are just convenience fields, so we can derive them if they aren't included in the file.

The other differences don't matter.  I used the long form with `X` and `=` for match/mismatching positions instead of `M` for both. Either way is good. Also, the igblast result has the trailing `S` operator which I skipped. Again, I think either way is fine. Though, I'd probably add a trailing `N` operator too if you want to keep the trailing `S`.

**Comment by jianye00** [comment] 2018-03-16 20:22
@javh It seems adding N to indicate the leading and trailing unaligned subject region is fine.  Your N is in front of S which is different than I thought.  Shouldn't the order be query (S) first and then subject (N)?    At least the standard alignment way is to put query on top of subject sequence.

**Comment by javh** [comment] 2018-03-16 20:32
@jianye00, we made a completely arbitrary decision on whether `N` or `S` should be first.

I don't mind at all if we want to reverse the order. Assuming no one else voices a concern, I can switch my code to `S` then `N`, and update the AIRR docs accordingly.

**Comment by jianye00** [comment] 2018-03-16 21:22
@javh Ok, if there is no real need for the current order,  I'd suggest putting query in front of subject just to make it more intuitive.

**Comment by laserson** [comment] 2018-03-22 00:35
I am opposed to "relitigating" the zero- vs one-based coordinates. People were overwhelmingly in favor of zero-based, and I would stick with that. Also, this should be separate from an "API" for loading the data. The default "API" IMO should be that someone uses a CSV reader to load up the data (e.g., pandas or R's dataframe), which will then likely be consumed by another tool.

**Comment by javh** [comment] 2018-03-22 19:51
Swapped the order of `N` and `S` operators in the CIGAR string in #94.

**Comment by jianye00** [comment] 2018-04-02 19:00
Looking at the new specs http://airr-formats.readthedocs.io/en/api-docs/formats/rearrangements.html ,  I see a few things here:

1.  sequence_aa...I thought the definition needs to be clarified.  We'd need to output the translated amino acids (i.e., the a.a. line above the nucleotide sequence alignment in igblast default format) that starts from the start of V through end of J.  Can we use this field for our purpose?

2.  fields for global alignment such as sequence_alignment is not something igblast produces since igblast is a local alignment tool.  However,  we can produce alignment strings for each v, d, j alignments individually (this is in addition to individual v,d, j CIGAR alignment).  I don't see such fields.  I'd suggest adding v_sequence_alignment, v_germline_alignment, etc.  we could also add the corresponding alignment coordinate (i.e., v_sequence_alignment_end, v_germline_alignment_end, etc).

**Comment by javh** [comment] 2018-04-03 15:56
@jianye00,

1.  For sample aligners, perhaps, but I think using `sequence_aa` for this purpose would be incorrect for IgBLAST specifically, because then the fields like `v_sequence_start` and `v_sequence_end` would be incorrect (the coordinates wouldn't match what's in `sequence`).  The correct field for this looks to be `sequence_alignment_aa`, if I understand your question correctly.  You mean the second line of the following, except with the concatenated V+NP1+D+NP2+J sequence, correct?

```
                                      <FR1-IMGT><--------CDR1-IMGT--------><--------------------FR2-IMGT---------------------><C
                                        T  G  S  T  S  X  L  G  S  G  C  X  V  H  W  Y  Q  H  F  P  G  X  A  P  K  L  L  I  F  S
                    Query_1      15   CACTGGNAGTACCTCCANCCTCGGGTCNGGTTGTNATGTACACTGGTACCAGCACTTTCCAGGANCAGCCCCCAAACTGCTCATCTTTAG  104
V  90.6% (211/233)  IGLV1-40*01  66   ......G..C.G.....A.A.....G.A....A.G...................GC........A.............C.......A.G.  155
                                        T  G  S  S  S  N  I  G  A  G  Y  D  V  H  W  Y  Q  Q  L  P  G  T  A  P  K  L  L  I  Y  G
V  90.6% (211/233)  IGLV1-40*02  66   ......G..C.G.....A.A.....G.A....A.G...................GC........A.............C.......A.G.  155
V  90.4% (208/230)  IGLV1-40*03  66   ......G..C.G.....A.A.....G.A....A.G...................GC........A.............C.......A.G.  155
```

`sequence_aa` would be the full query sequence translation.

2. Sure, I think it'll be fine to add the local alignment fields `v_sequence_alignment`, `v_germline_alignment`, etc. You shouldn't need the start/end fields though, as those already exists as `v_sequence_start` (query start), `v_germline_start` (subject start), etc.

Sounds like you might need to add `sequence_alignment` anyway to get `sequence_alignment_aa`?

**Comment by javh** [comment] 2018-04-04 17:07
Segment specific alignment fields added in #103.

**Comment by jianye00** [comment] 2018-04-05 19:55
@javh 

After further reviewing, we can actually assemble and output full alignment strings (encompassing v, d and j) as your new format specifies even though igblast does not produces some of these per se (for example the full alignment including germline v, d and j segments).   We can also produce the alignment coordinates (taking account of any deletions/insertions) for each v, d, j elements in the full alignment.  

But it looks some field names need to be changed.  Currently, sequence_alignment and germline_alignment are the holders for full alignment and fields like  v_alignment_end are for the full alignment coordinates.  Since we also want to produce individual alignment for v, d, and j elements,  I'd suggest to use something like full_sequence_alignment and full_germline_alignment rather than sequence_alignment and germline_alignment (also use v_full_alignment_end rather than  v_alignment_end for coordinates).  That would be more clear and possibly spare the names for us to add individual alignment fields.  We could then use fields like v_sequence_alignment, d_sequence_alignment  for individual alignment.  If we want to, we could also use something like v_alignment_end (currently in use to indicate the full alignment coordinates) for coordinates in individual alignment.

The individual alignment fields we want to include are:

v_sequence_alignment
v_germline_alignment
d_sequence_alignment
d_germline_alignment
j_sequence_alignment
j_germline_alignment

**Comment by javh** [comment] 2018-04-05 20:28
Hey @jianye00, that's great! Removes the need for post-processing to get the full sequence alignment.

I went ahead and added those `v/d/j/c_sequence_alignment`, `v/d/j/c_germline_alignment`  fields to the spec along with the associated `_aa` fields. I think I'd prefer to leave the full length alignments without qualifying them as `full_` for simplicity (to prevent core field names from getting too long, so custom derivatives aren't even longer).

I'm not sure there is a use case for having a field that defines the V/D/J start and J/D/J end in `v/d/j_sequence_alignment` because those values will always be `0` and `len(v/d/j_sequence_alignment)` and you wouldn't use that information for anything. Not that I can think of anyway... Correct me if I'm missing something.

Oh, and I'm thinking we should probably remove `c_call`, `c_score` and `c_cigar` from the required list. Most tools don't output those. Gotta see how the community feels about that though.

**Comment by javh** [comment] 2018-04-05 20:29
BTW - The docs at the official site are now current:

http://docs.airr-community.org/en/latest/formats/rearrangements.html

**Comment by jianye00** [comment] 2018-04-05 20:44
Alignment coordinates for individual alignments are not something I think are necessary (that's why we did not add these) but I was just to try to be more cautious in covering everything, probably over-cautious.  If that's not a concern, then you don't have to add full_.  Whatever you do with c_thing I am  ok since we don't deal with that.

**Comment by jianye00** [comment] 2018-04-16 18:37
We now have a pre-release igblast binary (linux only) conforming to the new airr format  on ftp://ftp.ncbi.nih.gov/blast/temp/igblast/ .  The binary is igblastn.2 and the sample output is temp.SRR1383447.fasta.airr (about 2M sequences).  Full-release will come soon.  Let me know if you see any issues.

**Comment by javh** [comment] 2018-04-16 18:48
Fantastic! 

I'm going to merge #106 tomorrow which will finalize the spec. I'll pull down the igblast development version and look at it tomorrow as well.

**Comment by javh** [comment] 2018-04-18 14:56
Okay, I merged in #106 and the spec should now be **frozen**.  The only impact on your output should be:

1. You can remove the `c_call`, `c_score`, `c_identity`, `c_cigar` columns. They aren't required anymore. (Or you can leave them if you want to.)
2. Rename `<v,d,j>_evalue` to `<v,d,j>_support`.

I skimmed through the example output and it looks good to me. I'll try to do a more detailed test run and comparison later today.

**Comment by javh** [comment] 2018-04-18 18:26
I did some more careful spot checks and everything looks good except your `_end` positions look off by +1. For 1-based, closed intervals (blast, R):

```
_start = 6
_end = 10
_length = 5 (includes positions 6,7,8,9,10)
```

For 0-based, half-open intervals (spec, python):

```
_start = 5
_end = 10
_length = 5 (includes positions 5,6,7,8,9)
``` 

I'll email you a link to the files I tested separately. Just for reference.  Everything else seems to match up!

**Comment by jianye00** [comment] 2018-04-19 18:50
After talking to Jason to clarify the numbering schema, we have now fixed the position discrepancy.    Also did the followings as requested:
remove the c_call, c_score, c_identity, c_cigar columns. 
Rename <v,d,j>_evalue to <v,d,j>_support.

The new linux igblast binary igblastn.3 is ftp://ftp.ncbi.nih.gov/blast/temp/igblast/ 
Again, let me know if you notice any issues.

**Comment by javh** [comment] 2018-04-22 18:30
Thanks, @jianye00. I'll run some tests in a few days (sorry for the slow - a bit behind). 

I suspect we're good though.

**Comment by javh** [comment] 2018-04-25 17:55
@jianye00, everything looks good to me. Everything seems to match up with my results, so we're either both wrong or both right. :)

The only difference I noticed you have identity as a percentage (`v_identity=99.661`) and I have it as a faction (`v_identity=0.99661`).  I don't think the community ever discussed which they wanted. I'm inclined to say either way is fine, because it's obvious from context. The `*_score` and `*_support` fields are context dependent too.

**Comment by javh** [comment] 2018-04-25 18:15
Sounds good to me. Going to close this issue then, because I think we are resolved. 

Reopen (or make a new one) if something comes up.

**Closed by javh** 2018-04-25 18:15 UTC
Labels: Formats, release priority
