### ISSUE TITLE
Cell Object and Rearrangement definition

### ISSUE THREAD

**Issue by sharikrish** [airr-community/airr-standards#360] opened 2020-03-24 09:18 UTC
`Cell `schema is currently available for review in #358 and in addition to this we need to clarify on `Cell `and `Rearrangement `object definition in the schema. 

One of the questions to clarify is that, if a Rearrangement is defined as an observed nucleic acid how do we represent UMI- and CellID-based collapsing.

On our last MinStd call we discussed that `Rearrangement` should represent rearrangements at DNA level (i.e. one biological entity per cell) while transcript and reads are derivatives or measurement artifacts. This would mean that `rearrangement` is always after UMI- and CellID collapsing and would these be defined as separate object in the schema?

**Comment by scharch** [comment] 2020-03-24 18:27
Currently the schema very clearly uses `Rearrangement` for both, and I don't understand why we need separate objects. In addition to `Read`, `UMI_consensus`, and `Cell_consensus`, would we also need a `Clustered_Read` object for downsampling bulk reads without UMIs? All of these would have exactly the same fields, wouldn't they?

**Comment by javh** [comment] 2020-03-26 00:43
Yeah, as @scharch said, `Rearrangement` records don't have to be at any particular level of analysis. They are annotated data. The metadata should define what kind of filtering/assembly/consensus/etc procedures the data went through.

**Comment by bcorrie** [comment] 2020-04-24 00:32
OK, catching up on my Cell issues - I have been neglecting them...

As far as the `Rearrangement` object in the spec goes, my understand is that it captures all of these. OMG, I agree with both @javh and @scharch 8-)

**Comment by bussec** [comment] 2020-04-27 12:34
So for clarification: A `rearrangement` can be a number of types (raw, *_consensus, etc.) but it is expected that all `rearrangements` linked to a `cell` are of the same type. Is this correct?

So in this case, how could I provide both the *n* raw and the 1 consensus for a given locus?

**Comment by javh** [comment] 2020-04-27 20:34
Yeah, though I might phrase it as all Rearrangements within a file/Repertoire will be of the same type. So by virtue of a Cell being associated with a single Repertoire, it's also associated with a single type of Rearrangement. I guess you could have a malformed Repertoire which is a mix of duplicate data at different data processing levels, but I don't think that's the schema's problem to solve.

I'm not seeing a good way to link raw reads and consensus sequences within the schema. But, I guess, what's the problem that needs to be solved?  Rearrangement records will be after processing, alignment and annotation. Raw reads will be before those steps. So how do we arrive at having annotated sequences with mixed levels of analysis in the first place?  Can this problem be solved by just using multiple `*_count` fields? Eg, raw reads, UMIs, and duplicate consensus sequences.

**Comment by scharch** [comment] 2020-04-28 18:36
> Yeah, though I might phrase it as all Rearrangements within a file/Repertoire will be of the same
> type. So by virtue of a Cell being associated with a single Repertoire, it's also associated with a
> single type of Rearrangement. I guess you could have a malformed Repertoire which is a mix of
> duplicate data at different data processing levels, but I don't think that's the schema's problem to
> solve.

Agreed.

> I'm not seeing a good way to link raw reads and consensus sequences within the schema. But,
> guess, what's the problem that needs to be solved? 

This has come up several times now. I think the problem is reproducibility/verification and the answer is proper use of the `data_processing` object in the metadata.

**Comment by bussec** [comment] 2020-05-01 19:12
>> I'm not seeing a good way to link raw reads and consensus sequences within the schema. But, guess, what's the problem that needs to be solved?

> This has come up several times now. I think the problem is reproducibility/verification and the answer is proper use of the data_processing object in the metadata.

IMO there are two problems:
* The first one is that of reproducibility, which could be solved if `data_procession` contains enough information that the result (consensus) can be derived from the raw reads with high reliabilty. The problem for single-cell is, that the usual pre-/post-processing split is not so simple, because you require some level of processing for the assignment to the cell.
* The second one is that there are good reasons for both sequences types. If I am mainly interested in the actual receptor, I would like to have a single consensus sequence of each chain, not 392 raw reads that I need to collapse. However, other people might be interested in the raw reads, as the collapsing might remove important information for them (mutations, editing, splicing).
As we are designing a `Receptor` object, there should be a standard whether this refers to exact 2 collapsed sequences or to multiple raw reads, and I think that most users would expect the former one.

The easy solution for the near-term, would be to through away raw and only use collapsed, but this will make export/import cycles via the standard format lossy for us (as sciReptor stores both sequence type separately).

**Comment by javh** [comment] 2020-05-01 19:28
> As we are designing a `Receptor` object, there should be a standard whether this refers to exact 2 collapsed sequences or to multiple raw reads, and I think that most users would expect the former one.

Yeah, I think that would be the expectation as well. Rearrangement records are specifically intended to be the "truth" representation; ie, the best inference of what was sequenced, after decisions have been made about what the best gene assignment is, what the correct consensus sequence is, etc. 

`Alignment` exists specifically to house more complete data about gene alignments, because that's outside the scope of `Rearrangement`. We may have to something similar for mapping whatever is in `Rearrangement` back to raw reads.

Maybe the need for mapping back to raw reads and/or contigs is something we can address through the redesign of DataProcessing:
https://github.com/airr-community/airr-standards/projects/8

**Comment by bcorrie** [comment] 2020-05-02 17:36
> > I'm not seeing a good way to link raw reads and consensus sequences within the schema. But,
> > guess, what's the problem that needs to be solved?
> 
> This has come up several times now. I think the problem is reproducibility/verification and the answer is proper use of the `data_processing` object in the metadata.

I think I would agree... For a given set of N annotated reads (and therefore N Rearrangement records) without collapsing to a consensus sequence, I would envision a specific data_processing (DP1) attached to those rearrangement records. If those reads are then collapsed to M consensus sequences using another data_processing pipeline (DP2), then I would envision another M Rearrangement records representing these consensus sequences.

So a total of N + M Rearrangement records, N of them associated with DP1 and M of them associated with DP2. If one only cared about one or the other, you might actually store only N/DP1 or you might only store M/DP2.

The schema currently handles this fine, with the exception of DataProcessing perhaps not being rich enough to capture the subtleties of the different DPs, as it was originally designed to capture one step and focused on the first one...

**Comment by bcorrie** [comment] 2024-02-06 20:29
Any thoughts on whether this can be closed or not? This doesn't seem like it has been resolved, but I also don't think that any changes are likely to be done for this before v2.0. So I would suggest either closing or removing the v2.0 tag.

**Comment by javh** [comment] 2024-02-11 17:57
I think we can skip this.

**Closed by javh** 2024-02-11 17:57 UTC

**Comment by bussec** [comment] 2024-02-11 23:21
As discussed above, to resolve this we would need a distinction between "raw" and "processed" data and would need to be able to hold both of them at the same time (i.e., treat them as different entities). This won't happen for v2.0. If it is still an issue in 2026, open a new issue for it ;-)
