### ISSUE TITLE
Inconsistencies in YAML vs TSV

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#19] opened 2017-10-08 23:43 UTC
The Travis job found some inconsistencies:

https://travis-ci.org/airr-community/airr-standards/builds/285271493

cc @schristley @BusseChristian @ahmadchan

**Comment by laserson** [comment] 2017-10-09 01:53
Copying and pasting here to make it easier.

```
read_direction                 is found in yaml but not tsv
paired_filename                is found in yaml but not tsv
paired_read_direction          is found in yaml but not tsv
filename                       is found in yaml but not tsv
collapsing method              is found in yaml but not tsv
whole_vs_partial sequences     is found in yaml but not tsv
nucleic_acid_processing_id     is found in yaml but not tsv
cell_processing_id             is found in yaml but not tsv
collapsing_method              is found in tsv but not yaml
cell_index                     is found in tsv but not yaml
duplicate_count                is found in tsv but not yaml
d_allele                       is found in tsv but not yaml
c_allele                       is found in tsv but not yaml
junction_nt                    is found in tsv but not yaml
germline_database              is found in tsv but not yaml
v_allele                       is found in tsv but not yaml
j_allele                       is found in tsv but not yaml
junction_aa                    is found in tsv but not yaml
complete_sequences             is found in tsv but not yaml
```

**Comment by laserson** [comment] 2017-10-09 12:47
Here are the remaining ones:

```
cell_processing_id             is found in yaml but not tsv
paired_read_direction          is found in yaml but not tsv
paired_filename                is found in yaml but not tsv
filename                       is found in yaml but not tsv
read_direction                 is found in yaml but not tsv
nucleic_acid_processing_id     is found in yaml but not tsv
j_allele                       is found in tsv but not yaml
junction_aa                    is found in tsv but not yaml
junction_nt                    is found in tsv but not yaml
cell_index                     is found in tsv but not yaml
c_allele                       is found in tsv but not yaml
d_allele                       is found in tsv but not yaml
germline_database              is found in tsv but not yaml
duplicate_count                is found in tsv but not yaml
v_allele                       is found in tsv but not yaml
```

**Comment by schristley** [comment] 2017-10-09 16:50
There are going to be more fields in the yaml file versus the tsv because the tsv does not explicitly list the relationships between the entities. This explains fields like `cell_processing_id` and `nucleic_acid_processing_id`.

I also added additional fields for the FASTQ raw sequence files. We can debate which fields are needed but I added those which VDJServer uses so that it knows how to properly interpret the raw sequence files.

**Comment by schristley** [comment] 2017-10-09 16:52
I didn't add a definition for rearrangement annotations in the yaml file as I'm assuming that definition will be coming from the airr-formats repo.

**Comment by BusseChristian** [comment] 2017-10-10 16:24
I am not sure whether there will be a lot of fixed formats for the rearrangement annotation. IMO in the end it is down to:
`[vdjc]_allele` : string   (as there is no fixed reference database, the format is rather unpredictable)
`junction_(aa|nt)` : string    (random characters [A-Z])
`cell_index` + `duplicate_count` : integer
`germline_database` : string   (should contain name, version and date; maybe an URL?)

Am I missing something?

**Comment by bcorrie** [comment] 2017-10-13 02:25
Would it make sense to keep a YAML file that maps exactly to the TSV file and then have other YAML files that contain the other aspect of the definition that are required to make things work for other purposes. Essentially an abstraction and functional layering that one can compose into the set of definitions that one cares about for a specific purpose.

That way the Travis consistency check for the actual MiAIRR TSV to YAML can be confirmed exactly (MiAIRR.tsv -> MiAIRR.yaml).

We could then have an ancillary YAML file for the rearrangements that extends the 9 MiAIRR defined rearrangement fields to include the extensions required for further processing (MiAIRR.YAML + MiAIRR-rearrangement.yaml).

In the same manner, we could have a "relationships" YAML file that separately lists the relationships between the MiAIRR entities (MiAIRR.yaml + MiAIRR-relationships.yaml).

Similarly for the VDJServer required fields you  could then have MiAIRR.yaml + MiAIRR-rearrangements.yaml + MiAIRR-relationships.yaml + AIRR-VDJServer.yaml to give you the fields "... which VDJServer uses so that it knows how to properly interpret the raw sequence files."

For iReceptor's API, we would include MiAIRR.yaml + MiAIRR-rearrangements.yaml + MiAIRR-relationships.yaml and then any additional fields/features we would require for our specific functionality (iReceptor.yaml). This is essentially what our swagger API definition does for the /samples API entry point (using the MiAIRR yaml file), and I hope to add the MiAIRR Formats rearrangement.yaml file to our definition of the /sequences API entry point next week.

As more consistency becomes apparent, more features will move into the composable layers, and there will be less and less need for the tool and domain specific files (or at least they will shrink in scope). But I think we want to avoid one large definition,  and instead use layered definitions that one can compose for tools or applications. It seems to me that the base layer should be the MiAIRR field definitions from the TSV file without any imposed structure (the Minimal Standard 8-)

**Comment by schristley** [comment] 2017-10-27 19:31
Consistency checks have been rewritten to be more explicit about the mapping between TSV and YAML. Committed to development branch.

**Closed by schristley** 2017-10-27 19:31 UTC
